name: "Podcast Generator"
author: "Rally Villalobos"
description: "Generates a feed for podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
input:
  email:
    description: The commiter's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The comitter's name
    required: true
    default: ${{ github.actor }}
